//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TestBed.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TESTBETYPE                  129
#define IDC_HAND                        130
#define IDD_DIALOG1                     131
#define IDC_STC1                        1000
#define IDC_TCOLOR                      1002
#define IDC_BCOLOR                      1003
#define IDC_TULINE                      1004
#define IDC_ITALICS                     1005
#define IDC_FNAME                       1006
#define IDC_BOLD                        1007
#define IDC_BORDER                      1008
#define IDC_NN                          1008
#define IDC_SUNKEN                      1009
#define IDC_MONTY                       1011
#define IDC_FSIZE                       1012
#define IDC_FLASH                       1013
#define IDC_LINK                        1014
#define IDC_XX                          1015
#define IDC_X0_D0                       1017
#define IDC_X0_D1                       1018
#define IDC_X0_D2                       1019
#define IDC_X0_D3                       1020
#define IDC_X0_D4                       1021
#define IDC_X0_D5                       1022
#define IDC_X0_D6                       1023
#define IDC_X0_D7                       1024
#define IDC_X0_D8                       1025

#define IDC_X1_D0                       1031
#define IDC_X1_D1                       1032
#define IDC_X1_D2                       1033
#define IDC_X1_D3                       1034
#define IDC_X1_D4                       1035
#define IDC_X1_D5                       1036
#define IDC_X1_D6                       1037
#define IDC_X1_D7                       1038
#define IDC_X1_D8                       1039

#define IDC_X2_D0                       1040
#define IDC_X2_D1                       1041
#define IDC_X2_D2                       1042
#define IDC_X2_D3                       1043
#define IDC_X2_D4                       1044
#define IDC_X2_D5                       1045
#define IDC_X2_D6                       1046
#define IDC_X2_D7                       1047
#define IDC_X2_D8                       1048

#define IDC_X3_D0                       1049
#define IDC_X3_D1                       1050
#define IDC_X3_D2                       1051
#define IDC_X3_D3                       1052
#define IDC_X3_D4                       1053
#define IDC_X3_D5                       1054
#define IDC_X3_D6                       1055
#define IDC_X3_D7                       1056
#define IDC_X3_D8                       1057


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
